language: php
php:
  - 5.4
  - 5.5
  - 5.6
install: composer install
script: ./vendor/bin/phing
after_script:
  - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then ./vendor/bin/coveralls -vvv; fi;
notifications:
  email:
    recipients:
      - kristof@2dotstwice.be
